feat: add description to metadata
kptdobe/helix-importer-projects pull request #13
Opened 2021-08-17 15:41 UTC by fkakatie

#11

2021-08-17 15:48 UTC, kptdobe requested changes
Test ?

2021-08-17 16:54 UTC, fkakatie commented
@kptdobe Want to merge the tests PR before rewriting a test in _this_ PR.

2021-08-18 21:30 UTC, fkakatie commented on test/blogtoblog/BlogToBlogImport.spec.ts
> +    strictEqual(document.head.innerHTML + document.body.innerHTML, expected);
after much trial and error, this is what I can up that would actually allow me to run the tests. let me know what you think.

2021-08-19 08:09 UTC, kptdobe approved these changes

2021-08-19 16:57 UTC, merged